# Form implementation generated from reading ui file 'createtaskwindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CreateTaskWindow(object):
    def setupUi(self, CreateTaskWindow):
        CreateTaskWindow.setObjectName("CreateTaskWindow")
        CreateTaskWindow.resize(400, 360)
        self.RoundRectangle = QtWidgets.QFrame(parent=CreateTaskWindow)
        self.RoundRectangle.setGeometry(QtCore.QRect(20, 20, 361, 331))
        self.RoundRectangle.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.RoundRectangle.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.RoundRectangle.setObjectName("RoundRectangle")
        self.DescrptionLabel = QtWidgets.QLabel(parent=self.RoundRectangle)
        self.DescrptionLabel.setGeometry(QtCore.QRect(10, 60, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.DescrptionLabel.setFont(font)
        self.DescrptionLabel.setObjectName("DescrptionLabel")
        self.DescriptionEdit = QtWidgets.QTextEdit(parent=self.RoundRectangle)
        self.DescriptionEdit.setGeometry(QtCore.QRect(180, 60, 171, 31))
        self.DescriptionEdit.setObjectName("DescriptionEdit")
        self.DateLabel = QtWidgets.QLabel(parent=self.RoundRectangle)
        self.DateLabel.setGeometry(QtCore.QRect(10, 110, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.DateLabel.setFont(font)
        self.DateLabel.setObjectName("DateLabel")
        self.DateEdit = QtWidgets.QDateEdit(parent=self.RoundRectangle)
        self.DateEdit.setGeometry(QtCore.QRect(180, 110, 171, 31))
        self.DateEdit.setObjectName("DateEdit")
        self.TimeEdit = QtWidgets.QTimeEdit(parent=self.RoundRectangle)
        self.TimeEdit.setGeometry(QtCore.QRect(180, 150, 171, 31))
        self.TimeEdit.setObjectName("TimeEdit")
        self.TimeLabel = QtWidgets.QLabel(parent=self.RoundRectangle)
        self.TimeLabel.setGeometry(QtCore.QRect(10, 150, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.TimeLabel.setFont(font)
        self.TimeLabel.setObjectName("TimeLabel")
        self.IntervalLabel = QtWidgets.QLabel(parent=self.RoundRectangle)
        self.IntervalLabel.setGeometry(QtCore.QRect(10, 190, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.IntervalLabel.setFont(font)
        self.IntervalLabel.setObjectName("IntervalLabel")
        self.IntervalEdit = QtWidgets.QTextEdit(parent=self.RoundRectangle)
        self.IntervalEdit.setGeometry(QtCore.QRect(180, 190, 171, 31))
        self.IntervalEdit.setObjectName("IntervalEdit")
        self.PriorityLabel = QtWidgets.QLabel(parent=self.RoundRectangle)
        self.PriorityLabel.setGeometry(QtCore.QRect(10, 230, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.PriorityLabel.setFont(font)
        self.PriorityLabel.setObjectName("PriorityLabel")
        self.PriorityEdit = QtWidgets.QTextEdit(parent=self.RoundRectangle)
        self.PriorityEdit.setGeometry(QtCore.QRect(180, 230, 171, 31))
        self.PriorityEdit.setObjectName("PriorityEdit")
        self.SubmitTask = QtWidgets.QPushButton(parent=self.RoundRectangle)
        self.SubmitTask.setGeometry(QtCore.QRect(20, 280, 321, 31))
        self.SubmitTask.setObjectName("SubmitTask")
        self.TaskLabel = QtWidgets.QLabel(parent=self.RoundRectangle)
        self.TaskLabel.setGeometry(QtCore.QRect(10, 20, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.TaskLabel.setFont(font)
        self.TaskLabel.setObjectName("TaskLabel")
        self.TaskEdit = QtWidgets.QTextEdit(parent=self.RoundRectangle)
        self.TaskEdit.setGeometry(QtCore.QRect(180, 20, 171, 31))
        self.TaskEdit.setObjectName("TaskEdit")

        self.retranslateUi(CreateTaskWindow)
        QtCore.QMetaObject.connectSlotsByName(CreateTaskWindow)

    def retranslateUi(self, CreateTaskWindow):
        _translate = QtCore.QCoreApplication.translate
        CreateTaskWindow.setWindowTitle(_translate("CreateTaskWindow", "Create a New Task"))
        self.DescrptionLabel.setText(_translate("CreateTaskWindow", "Description"))
        self.DateLabel.setText(_translate("CreateTaskWindow", "Date"))
        self.TimeLabel.setText(_translate("CreateTaskWindow", "Time"))
        self.IntervalLabel.setText(_translate("CreateTaskWindow", "Interval"))
        self.PriorityLabel.setText(_translate("CreateTaskWindow", "Priority"))
        self.SubmitTask.setText(_translate("CreateTaskWindow", "Create Task"))
        self.TaskLabel.setText(_translate("CreateTaskWindow", "Task Name"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CreateTaskWindow = QtWidgets.QFrame()
    ui = Ui_CreateTaskWindow()
    ui.setupUi(CreateTaskWindow)
    CreateTaskWindow.show()
    sys.exit(app.exec())
