# Form implementation generated from reading ui file 'task.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TaskBox(object):
    def setupUi(self, TaskBox):
        TaskBox.setObjectName("TaskBox")
        TaskBox.resize(666, 75)
        self.TaskName = QtWidgets.QLabel(parent=TaskBox)
        self.TaskName.setGeometry(QtCore.QRect(80, 30, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.TaskName.setFont(font)
        self.TaskName.setObjectName("TaskName")
        self.pushButton = QtWidgets.QPushButton(parent=TaskBox)
        self.pushButton.setGeometry(QtCore.QRect(20, 20, 31, 31))
        self.pushButton.setObjectName("pushButton")
        self.DateLabel = QtWidgets.QLabel(parent=TaskBox)
        self.DateLabel.setGeometry(QtCore.QRect(370, 30, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.DateLabel.setFont(font)
        self.DateLabel.setObjectName("DateLabel")
        self.TimeLabel = QtWidgets.QLabel(parent=TaskBox)
        self.TimeLabel.setGeometry(QtCore.QRect(430, 30, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TimeLabel.setFont(font)
        self.TimeLabel.setObjectName("TimeLabel")
        self.EditButton = QtWidgets.QPushButton(parent=TaskBox)
        self.EditButton.setGeometry(QtCore.QRect(500, 30, 51, 24))
        self.EditButton.setObjectName("EditButton")
        self.DeleteButton = QtWidgets.QPushButton(parent=TaskBox)
        self.DeleteButton.setGeometry(QtCore.QRect(570, 30, 51, 24))
        self.DeleteButton.setObjectName("DeleteButton")

        self.retranslateUi(TaskBox)
        QtCore.QMetaObject.connectSlotsByName(TaskBox)

    def retranslateUi(self, TaskBox):
        _translate = QtCore.QCoreApplication.translate
        TaskBox.setWindowTitle(_translate("TaskBox", "Frame"))
        self.TaskName.setText(_translate("TaskBox", "TextLabel"))
        self.pushButton.setText(_translate("TaskBox", "cir"))
        self.DateLabel.setText(_translate("TaskBox", "date"))
        self.TimeLabel.setText(_translate("TaskBox", "time"))
        self.EditButton.setText(_translate("TaskBox", "edit"))
        self.DeleteButton.setText(_translate("TaskBox", "del"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TaskBox = QtWidgets.QFrame()
    ui = Ui_TaskBox()
    ui.setupUi(TaskBox)
    TaskBox.show()
    sys.exit(app.exec())
